asite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'asite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^ipts/', include('ipts.urls', namespace="ipts")),
)

ipts/urls.py
from django.conf.urls import patterns, url

from ipts import views

urlpatterns = patterns('',
		url(r'^$', views.index, name='index'),
		url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
		url(r'^(?P<pk>\d+)/results/$', views.results, name='results'),
		url(r'^(?P<pk>\d+)/chosen/$', views.chosen, name='chosen'),
		url(r'^resultsAll/$', views.resultsAll, name='resultsAll'),
)

ipts/models.py
from django.db import models

# Create your models here.

class Clinic(models.Model):
	cname = models.CharField(max_length=200)

	def __str__(self):
		return self.cname

class Choice(models.Model):
	clinic = models.ForeignKey(Clinic)
	choice_text = models.CharField(max_length=200)
	chosen = models.NullBooleanField()

	def __str__(self):
		return self.choice_text

ipts/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from ipts.models import Clinic, Choice
from django.http import HttpResponse, HttpResponseRedirect
#from django.template import Context, loader
#from django.http import Http404
from django.core.urlresolvers import reverse

def index(request):
	clinicList = Clinic.objects.all()
	#output = ', '.join([c.cname for c in clinicList])
	#return HttpResponse(output)
	#template = loader.get_template('ipts/index.html')
	#context = Context({
	#	'clinicList' : clinicList,
	#})
	#return HttpResponse(template.render(context))
	context = {'clinicList' : clinicList}
	return render(request, 'ipts/index.html', context)

def detail(request, pk):
	#return HttpResponse("You're looking at clinic %s." %pk)
	#try:
	#	clinic = Clinic.objects.get(pk=pk)
	#except Clinic.DoesNotExist:
	#	raise Http404
	clinic = get_object_or_404(Clinic, pk=pk)
	return render(request, 'ipts/detail.html', {'clinic':clinic})

def results(request, pk):
	#return HttpResponse("You're looking at results of clinic chosen.")
	clinicList = Clinic.objects.all()
	clinic = get_object_or_404(Clinic, pk=pk)
	return render(request, 'ipts/results.html', {
		'clinic':clinic,
		'clinicList':clinicList,
	})

def chosen(request, pk):
	#return HttpResponse("You're choosing the %s." %pk)
	c = get_object_or_404(Clinic, pk=pk)
	d = c.choice_set.all()
	for choice in d:
		choice.chosen = False
		choice.save()
	try:
		selectedChoice = c.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'ipts/detail.html', {
			'clinic':c,
			'error_message': "You didn't select a choice.",
		})
	else:
		selectedChoice.chosen = True
		selectedChoice.save()
		return HttpResponseRedirect(reverse('ipts:results', args=(c.id,)))

def resultsAll(request):
	clinicList = Clinic.objects.all()
	return render(request, 'ipts/resultsAll.html', {
		'clinicList':clinicList,
	})

ipts/templates/ipts/detail.html
<h1>{{ clinic.cname }}</h1>

<!--<ul>
{% for choice in clinic.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>-->

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'ipts:chosen' clinic.id %}" method="post">
{% csrf_token %}
{% for choice in clinic.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Choose" />
</form>

ipts/templates/ipts/index.html
{% if clinicList %}
<ul>
	{% for clinic in clinicList %}
	<!--<li><a href="/ipts/{{ clinic.id }}/">{{ clinic.cname }}</a></li>-->
	<li><a href="{% url 'ipts:detail' clinic.id %}">{{ clinic.cname }}</a></li>
	{% endfor %}
</ul>

{% else %}
	<p>No polls are available.</p>
{% endif %}

ipts/templates/ipts/results.html
{% if clinicList %}
	{% for clinicL in clinicList %}
		{% if clinicL.id != clinic.id %}
		<ul>
			<li><a href="{% url 'ipts:detail' clinicL.id %}">{{ clinicL.cname }}</a></li>
		</ul>
		{% endif %}

		{% if clinicL.id = clinic.id %}
		<h1>{{ clinic.cname }}</h1>

			<ul>
			{% for choice in clinic.choice_set.all %}
				<li>{{ choice.choice_text }} -- {{ choice.chosen }}</li>
			{% endfor %}
			</ul>
		{% endif %}
	{% endfor %}
	<a href="{% url 'ipts:resultsAll' %}">Show All Result.</a>
{% endif %}

ipts/templates/ipts/resultsAll.html
{% if clinicList %}
	{% for clinic in clinicList %}
	<ul><li><a href="{% url 'ipts:detail' clinic.id %}">{{ clinic.cname }}</a>
		{% for choice in clinic.choice_set.all %}
			{% if choice.chosen == True %}
				{{ choice.choice_text }}
			{% endif %}
		{% endfor %}
	</li></ul>
	{% endfor %}
	<a href="{% url 'ipts:index' %}">Return to Index</a>
{% endif %}